version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports: 
      - '8000:8000'
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app