services:
  - type: docker
    name: db
    image: postgres:latest  
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
      - key: POSTGRES_DB
        value: postgres
    disk:
      name: pgdata
      mountPath: /var/lib/postgresql/data
    ports:
      - number: 5432
        protocol: tcp

  - type: docker
    name: redis
    image: redis/redis-stack-server:latest 
    ports:
      - number: 6379
        protocol: tcp

  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile  # Specify the path to your Dockerfile for the backend service
    buildCommand: docker build -t my-backend-image ./backend  # Specify the build command
    envVars:
      - key: PG_DB
        value: postgres
      - key: PG_USER
        value: postgres
      - key: PG_PASSWORD
        value: postgres
      - key: PG_HOST
        value: db
    ports:
      - number: 8000
        protocol: tcp
    disk:
      name: backend-data
      mountPath: /app
    dependsOn:
      - db
      - redis

volumes:
  - name: pgdata
  - name: backend-data
