name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.18, 3.10.13, 3.11.6,3.11.5, 3.12.0]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Commit and push changes (if any)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update dependencies"
        git push
        
    # - name: Run Tests
    #   run: |
    #     python manage.py test
