name: Backend Python-Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.11.5, 3.11.6, 3.11.7, 3.12.0, 3.12.1]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Run Flake8 (Linting)
        working-directory: ./backend
        run: |
          pip install flake8
          flake8 ./backend

      # - name: Run Tests
      #   run: |
      #     python manage.py test

  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build Docker Image
        run: docker build -t backend_image ./backend