name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.18, 3.10.13, 3.11.6,3.11.5, 3.12.0]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flake8 (Linting)
      run: |
       pip install flake8
       flake8 ./backend
        
    - name: Update dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for dependency updates
      run: |
          if [[ -n $(git diff --exit-code) ]]; then
            echo "Dependencies have been updated. Committing changes..."
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add .
            git commit -m "Update dependencies"
            git push
          else
            echo "No dependency updates found."
          fi

    # - name: Run Tests
    #   run: |
    #     python manage.py test
