name: Frontend React-TypeScript CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
        max-parallel: 4
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
          node-version: [21.5.0, 20.10.0, 19.9.0, 18.19.0]
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}

    - name: Install Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build React app
      working-directory: ./frontend
      run: npm run build

    # - name: Run tests
    #   run: npm test
